

name: CI/CD for GCP Services

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}


    # Step 3: Configure Docker for GCP Artifact Registry
    - name: Configure Docker
      run: gcloud auth configure-docker europe-docker.pkg.dev

    # Step 4: Build Docker Image
    - name: Build Docker Image
      run: docker build -t garp1:latest .

    # Step 5: Tag Docker Image
    - name: Tag Docker Image
      run: docker tag garp1:latest europe-docker.pkg.dev/aceinternal-2ed449d3/group-mapping/garp1:latest

    # Step 6: Push Docker Image to Artifact Registry
    - name: Push Docker Image
      run: docker push europe-docker.pkg.dev/aceinternal-2ed449d3/group-mapping/garp1:latest


    - name: Test
      run: echo "authenticating done"


  run_on_vm:
    # Define a separate job for VM-related tasks
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    # Step 1: Authenticate with GCP
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Step 2: SSH into VM and check logs for success
    - name: SSH to VM and Check Connection
      uses: appleboy/ssh-action@v0.1.7
      id: ssh_connection
      with:
        host: ${{ secrets.VM_EXTERNAL_IP }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }} # Or private key if using SSH key authentication
        port: 22
        script: |
          echo "Checking VM connection..."
          uname -a
          df -h
          echo "Successfully logged in to VM."

